name: Deploy Simple Chatbot

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Create simple site
        run: |
          mkdir -p public
          cp index.html public/ || echo "No index.html found, creating one..."
          
          if [ ! -f public/index.html ]; then
            cat > public/index.html << 'HTMLEOF'
<!DOCTYPE html>
<html>
<head>
    <title>AI Chatbot</title>
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <style>
        body { font-family: Arial, sans-serif; padding: 20px; background: #f5f5f5; }
        .container { max-width: 600px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; }
        .chat-btn { background: #2563eb; color: white; padding: 15px 30px; border: none; border-radius: 8px; cursor: pointer; }
        .chat-panel { margin-top: 20px; border: 1px solid #ddd; padding: 20px; border-radius: 8px; display: none; }
        .chat-panel.open { display: block; }
        .messages { height: 300px; overflow-y: auto; background: #fafafa; padding: 10px; margin-bottom: 10px; }
        .message { margin: 10px 0; padding: 10px; border-radius: 8px; }
        .message.user { background: #dbeafe; text-align: right; margin-left: 20%; }
        .message.bot { background: #f3f4f6; margin-right: 20%; }
        .input-area { display: flex; gap: 10px; }
        .input-area input { flex: 1; padding: 10px; border: 1px solid #ddd; border-radius: 4px; }
        .input-area button { padding: 10px 20px; background: #2563eb; color: white; border: none; border-radius: 4px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🤖 AI Assistant</h1>
        <p>Chat with our AI powered by Claude</p>
        <div id="app"></div>
    </div>

    <script>
        const { createApp, ref } = Vue;
        
        createApp({
            setup() {
                const isOpen = ref(false);
                const messages = ref([{ sender: 'bot', text: 'Hello! How can I help you?' }]);
                const userInput = ref('');
                const isLoading = ref(false);

                const toggleChat = () => isOpen.value = !isOpen.value;

                const sendMessage = async () => {
                    if (!userInput.value.trim()) return;
                    
                    const message = userInput.value.trim();
                    messages.value.push({ sender: 'user', text: message });
                    userInput.value = '';
                    isLoading.value = true;

                    try {
                        const response = await axios.post('https://w2yeklcbqa.execute-api.us-west-1.amazonaws.com/context/claude-enhanced', {
                            prompt: message
                        });
                        const botResponse = response.data.completion || 'No response received';
                        messages.value.push({ sender: 'bot', text: botResponse });
                    } catch (error) {
                        messages.value.push({ sender: 'bot', text: 'Error: ' + error.message });
                    } finally {
                        isLoading.value = false;
                    }
                };

                return { isOpen, messages, userInput, isLoading, toggleChat, sendMessage };
            },
            template: \`
                <div>
                    <button @click="toggleChat" class="chat-btn">
                        {{ isOpen ? 'Close Chat' : 'Open Chat' }}
                    </button>
                    <div class="chat-panel" :class="{ open: isOpen }">
                        <div class="messages">
                            <div v-for="msg in messages" class="message" :class="msg.sender">{{ msg.text }}</div>
                            <div v-if="isLoading">AI is thinking...</div>
                        </div>
                        <div class="input-area">
                            <input v-model="userInput" @keyup.enter="sendMessage" placeholder="Type here..." :disabled="isLoading">
                            <button @click="sendMessage" :disabled="isLoading">Send</button>
                        </div>
                    </div>
                </div>
            \`
        }).mount('#app');
    </script>
</body>
</html>
HTMLEOF
          fi
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
